# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Test2Windows.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


def showUpgrades():
    ui.widget.show()

def hideUpgrades():
    ui.widget.hide()


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setStyleSheet("""background: white;""")
        self.upgradesButton = QtWidgets.QPushButton(self.centralwidget)
        self.upgradesButton.setGeometry(QtCore.QRect(300, 120, 201, 121))
        self.upgradesButton.setObjectName("upgradesButton")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 800, 581))
        self.widget.setObjectName("widget")
        self.widget.setStyleSheet("""background: white;""")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(100, 40, 341, 191))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.goBackButton = QtWidgets.QPushButton(self.widget)
        self.goBackButton.setGeometry(QtCore.QRect(220, 320, 221, 91))
        self.goBackButton.setObjectName("goBackButton")
        self.goBackButton.raise_()
        self.label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.upgradesButton.clicked.connect(showUpgrades)
        self.goBackButton.clicked.connect(hideUpgrades)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.upgradesButton.setText(_translate("MainWindow", "Click to see upgrades"))
        self.label.setText(_translate("MainWindow", "Upgrades List"))
        self.goBackButton.setText(_translate("MainWindow", "Go back !"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    ui.widget.hide()
    sys.exit(app.exec_())
